spring:
  application:
    name: lifequest-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/lifequest_db
    username: postgres
    password: sejal@#1516

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true